### ISSUE TITLE
Canvas file reference lost when Loading/Saving

### ISSUE THREAD

**Issue by Salepate** [Baste-RainGames/Node_Editor#63] opened 2016-03-25 11:04 UTC
Hi,

Whenever Loading / Saving a canvas, there is that backup mechanic which create the LastSession.asset. This asset creation leads to losing the reference to the original asset for the currently edited canvas. Although its not a problem when saving. It displays the wrong information inside the Editor

![image](https://cloud.githubusercontent.com/assets/1110097/14043186/b8fb7070-f281-11e5-9392-94eaf71532b1.png)

Might be confusing for the end-user when editing multiple canvas.

Best Regards

**Comment by Seneral** [comment] 2016-03-25 11:28
Yep that was only caused in the last rewrite of the cache system and planned to fix this but yet did not found time for it... 
The problem is that the canvas name is always the name of the saved file. We could save it with it's original name so we would have to store additional information about the cache.
I can take a look how to fix this:)

**Comment by Salepate** [comment] 2016-03-25 13:06
I temporarily cached the name to bypass that side effect indeed.

keep up the good work

**Comment by Seneral** [comment] 2016-03-25 17:08
Cool! Maybe you can create a pull request? :)

**Comment by pi3butcher** [comment] 2016-07-05 15:05
Would this happen to be the same issue that causes these errors:

![image](https://cloud.githubusercontent.com/assets/3300071/16589275/685cf124-42a0-11e6-8c44-17e7d8208b00.png)

**Comment by Seneral** [comment] 2016-08-23 10:59
Planning on restoring some parts of the Cache System we had long ago, which basically saved the last canvas with it's name and stored the name in a string in the registry through editorprefs. It did work but when I changed it to lastsession.asset I did not realize at that point it would replace the name:/

**Comment by Seneral** [comment] 2016-12-10 12:27
Has been fixed in 8b065cd :)

**Closed by Seneral** 2016-12-10 12:27 UTC
Labels: bug, Current Focus, Difficulty Easy
