### ISSUE TITLE
GenericMenu in NodeEditor and RuntimeNodeEditor

### ISSUE THREAD

**Issue by pmhpereira** [Baste-RainGames/Node_Editor#29] opened 2016-01-26 19:14 UTC
When I use the NodeEditor window by itself, the contextual menu appears without any issues when pressing the right mouse button.

But, if I put Unity in Play Mode with a RuntimeNodeEditor, the contexual menu of the NodeEditor window doesn't appear anymore.

I looked into the code, but wasn't able to find a clue. :-)

**Comment by Seneral** [comment] 2016-01-26 19:16
Hm... I do have one... Do you get one on a fresh install?

**Comment by pmhpereira** [comment] 2016-01-26 19:18
On a fresh install it shows, but immediately disappears.

**Comment by Seneral** [comment] 2016-01-26 19:23
Hm, it totally works fine for me... and I have no clue what could cause this difference

**Comment by Seneral** [comment] 2016-01-26 19:25
Do you noticed other strange behaviour in the past? Not only related to this Node Editor?

**Comment by pmhpereira** [comment] 2016-01-26 19:36
I updated to the most recent version today (I had the one from before the huge update) and tried it.
It didn't work. I thought it was because of this version.
I tested with the previous one and it didn't work either. :D

Reproducible steps:

- Create new Unity project
- Create "Plugins" folder inside "Assets"
- Unzip the "Docs", "Editor" and "Node_Editor" to Assets\Plugins
- Add a RuntimeNodeEditor component to the "Main Camera" game object
- Uncheck "Specify Rect"
- Open the NodeEditor window through "Window/Node Editor"
- Right-clicking works fine in the NodeEditor window
- Start "Play" mode in Unity
- Right-clicking doesn't work anymore

**Comment by Seneral** [comment] 2016-01-26 19:43
Exact same Unity version, but works for me. May be because of windows 10 though, I'm running Windows 7 x64

**Comment by Seneral** [comment] 2016-01-26 19:45
Wait: I managed to reproduce it when I kept the Editor Window open though
Try to close it before hittin play, hopefully that will fix it

**Comment by Seneral** [comment] 2016-01-26 19:46
It actually may be the isue, as the class OverlayGUI, which handles all the related GUI, is static and keeps static references to the GenericMenu that is currently opened. Didn't explicitly test with multiple 'users' though...

**Comment by pmhpereira** [comment] 2016-01-26 19:48
Yes, I kept the NodeEditor window opened the whole time! Closing it solves it.

I wanted to test the ability to change a canvas in the NodeEditor and see it live reload in the RuntimeNodeEditor. That's why I needed the right-clicking. :-)

**Comment by Seneral** [comment] 2016-01-26 19:52
Ok, then I have to dissappoint though - due to how the save system works currently, this won't work without manual work. Currently, a working copy is created, because due to the nature of Scriptable objects, the link to the save file would cause the Node Editor to always modify the save without explicitly saving. So, I managed to break the link, but that will cause the Runtime and Editor version each to work on their own, individual copies.

**Comment by Seneral** [comment] 2016-01-26 19:54
I'll be 'redoing' the working copy system 'soon' though, so the actual last save file (which can be found in 'Plugins/Editor/Node_Editor/') will actually be the copy the Node editor is working on, so any changes to it would automatically reflect to all other users. Again, with manual setup (a bit), but a lot better than currently;)

**Closed by Seneral** 2016-01-26 19:54 UTC

**Comment by pmhpereira** [comment] 2016-01-26 19:58
I'm aware that's how it is working.

For what I need, I just have to re-open the same file in RuntimeNodeEditor after I saved it on the NodeEditor. It doesn't need to be always synchronized in both windows. But I still need both opened at the same time. :-)

**Comment by Seneral** [comment] 2016-01-26 20:10
Well, you could just load up NodeEditor.editor.mainNodeCanvas, which is the actual working copy that the currently opened editor window works on. Use that in the RuntimeComponent, maybe through a button, and that should work:)
Please report back if it does, would be interested! :)

**Comment by pmhpereira** [comment] 2016-01-26 20:29
But the right mouse button doesn't work. I can't add new nodes. :P

**Comment by Seneral** [comment] 2016-01-26 20:30
Dammit forgot:'D I'll try to find a quick fix for that...

**Comment by pmhpereira** [comment] 2016-01-26 20:31
Ahah, thanks for the help though! It's not really urgent. ;)
