### ISSUE TITLE
Duplicate Node (very rarely) causes two nodes to be created

### ISSUE THREAD

**Issue by pi3butcher** [Baste-RainGames/Node_Editor#83] opened 2016-07-14 16:01 UTC
I never had this happen to me, but once I passed the tool off to the content creators, they ran into this issue where 50% of the time, Duplicate Node would create an extra duplicate (two copies). Any idea what might be causing this or how I might fix it?

**Comment by Seneral** [comment] 2016-07-16 16:42
Sorry, missed it...
which branch are you using? I've tested the develop branch (the way to go as the master branch hasn't been synced for a long time) and it is working fine 100% of the time:/

**Comment by Seneral** [comment] 2016-07-16 16:45
Also tested the current master branch right now, fully working, even though the duplicated node is always at the top left (fixed in develop)

**Comment by Seneral** [comment] 2016-07-16 16:46
Can you send me the code of your nodes? Does it also happens on the defaul nodes?
Because I only could imagine a simple error in the initialization function to cause this, even though that wouldn't explain the irregularities (50%).
Thanks!

**Comment by pi3butcher** [comment] 2016-07-17 20:42
It's still working 100% for me also. The bug occurs on my colleague's machine. o.0 So it must be some sort of corrupt data or asset, right? The extra duplicate node appears on-top of the first duplicate node so it appears as if it worked until you drag the node and see the extra one.

BTW, I'm using development also. It can't be code related it if we have the same scripts and it works for me and not him, right? Let me find out if it happens with the standard nodes though - I'll get back to you Mon or Tues once I can test again on his machine. :)

**Comment by Seneral** [comment] 2016-07-18 15:35
I can't think of any data corruption that would affect duplication, but weird things may happen when using scene saving as it's relatively new. Can you send me the asset if it is asset related or the scene if the asset was saved to the scene?

**Comment by Seneral** [comment] 2016-07-26 18:40
I have an upcoming update on my side that might fix this, but I'm not sure. It depends on how your artist uses the framework...
It'll be ready soon;)

**Comment by pi3butcher** [comment] 2016-07-27 22:14
The team has been in crunch mode to release a milestone today, so haven't been able to bug the content developers for the past week or so, but the issue has yet to occur on my machine. :) But hopefully it fixes it! Once it's ready, you'll merge with the main branch and make a new release?

**Comment by Seneral** [comment] 2016-07-28 12:18
I hope I can do as long as it is stable enough. Last time I planned to do it it turned out not to be stable which resulted in another big delay as I couldn't find time to fix the new bugs. But hope is there;)

**Comment by Seneral** [comment] 2016-08-22 22:34
@pi3butcher Finally committed 336a537, the update I was talking about. Can you check if this fixes it for your colleague?

**Comment by Seneral** [comment] 2016-09-01 16:18
If not, please reopen, but for now I'll close as I've never been able to reproduce it:)

**Closed** 2016-09-02 14:36 UTC
